### ISSUE TITLE
Can add a command to change files to mp4?

### ISSUE THREAD

**Issue by xiaop1** [kfur/YtbDownBot#2]
First of all, the bot is really great.

But i want this command that can change a file to mp4. For example, when i download a video on bilibili.com, the video's format is flv so i cant watch it on telegram.

i use the ffmpeg in my Mac, and i know the changing file to another formate is too slowly. So i suggest that you can add a ten minutes limits to this changing command.

**Comment by kfur** [comment]
Video re-encoding is too resource expensive operation, my servers have only 512 MB RAM.
I think that ffmpeg will crash even if video 5 minutes length.

**Comment by kfur** [comment]
Added /m command.
